language: rust
rust:
  - nightly
  - beta
  - stable
env:
  - GTK=3.4
  - GTK=3.18
addons:
  apt:
    packages:
    - libgtk-3-dev
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ] && [ "$GTK" == "3.4" ]; then
    make regen_check;
    fi
  - mkdir .cargo
  - git clone -q --depth 50 -b pending https://github.com/EPashkin/examples _examples
  - cd _examples
  - python3 replace_patchs.py sys
  - ./build_travis.sh
